data:
  path: '../../src/data/dataset/dp_long.npz'
  n_samples: 420
  n_steps: 1501
  delay: 0
  double_precision: false

scaling:
  mode: "none"

weak_form:
  enabled: false  # Will be overridden by script
  parameters: [13, 2, 2, 2] # [N, dN, ordpol, ordint]

split:
  train_frac: 0.75

dataloader:
  batch_size: 32

model:
  name: 'comparison_model'  # Will be overridden by script
  type: "NN"
  encoder_layers: 1
  processor_layers: 1
  decoder_layers: 1
  latent_dimension: 32

training:
  n_epochs: 2000
  save_interval: 10
  load_checkpoint: true
  learning_rate: 1e-3
  ode_method: 'dopri5'
  rtol: 1e-7
  atol: 1e-9
  reconstruction_weight: 1.0
  dynamics_weight: 1.0 